refactor: prettier

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -1,52 +1,52 @@
 name: Build & Deploy
 
 on:
-  push:
-    branches: [ main ]
+    push:
+        branches: [main]
 
 env:
-  PERIOD: 10 # seconds
-  ATTEMPTS: 60 # PERIOD * ATTEMPTS = 600 s = 10 min
+    PERIOD: 10 # seconds
+    ATTEMPTS: 60 # PERIOD * ATTEMPTS = 600 s = 10 min
 
 jobs:
-  Build:
-    permissions:
-      contents: read
-      packages: read
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout sources
-        uses: actions/checkout@v4
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Build and push Docker image
-        id: push
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: |
-            ruskadijaspora/docker:portal-ui
-          build-args: NPM_TOKEN=${{ secrets.NPM_TOKEN }}
+    Build:
+        permissions:
+            contents: read
+            packages: read
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout sources
+              uses: actions/checkout@v4
+            - name: Login to Docker Hub
+              uses: docker/login-action@v3
+              with:
+                  username: ${{ vars.DOCKERHUB_USERNAME }}
+                  password: ${{ secrets.DOCKERHUB_TOKEN }}
+            - name: Build and push Docker image
+              id: push
+              uses: docker/build-push-action@v5
+              with:
+                  context: .
+                  file: ./Dockerfile
+                  push: true
+                  tags: |
+                      ruskadijaspora/docker:portal-ui
+                  build-args: NPM_TOKEN=${{ secrets.NPM_TOKEN }}
 
-  Deploy:
-    runs-on: ubuntu-latest
-    needs:
-      - Build
-    steps:
-      - name: install jq
-        run: sudo apt-get install jq
-      - name: start deploy
-        id: start_deploy
-        run: |
-          response=$(curl -s --request GET '${{ vars.COOLIFY_API_URL }}/api/v1/deploy?uuid=${{ vars.COOLIFY_SERVICE_ID }}&force=false' --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}')
-          deployment_uuid=$(echo $response | jq -r '.deployments[0].deployment_uuid')
-          if [[ $deployment_uuid == "null" ]]; then
-            printf "Failed to start deployment: \n$response"
-            exit 1
-          fi
-          echo "deployment_uuid=$deployment_uuid" >> $GITHUB_OUTPUT
+    Deploy:
+        runs-on: ubuntu-latest
+        needs:
+            - Build
+        steps:
+            - name: install jq
+              run: sudo apt-get install jq
+            - name: start deploy
+              id: start_deploy
+              run: |
+                  response=$(curl -s --request GET '${{ vars.COOLIFY_API_URL }}/api/v1/deploy?uuid=${{ vars.COOLIFY_SERVICE_ID }}&force=false' --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}')
+                  deployment_uuid=$(echo $response | jq -r '.deployments[0].deployment_uuid')
+                  if [[ $deployment_uuid == "null" ]]; then
+                    printf "Failed to start deployment: \n$response"
+                    exit 1
+                  fi
+                  echo "deployment_uuid=$deployment_uuid" >> $GITHUB_OUTPUT
